### ISSUE TITLE
[BUG]: scanFromPrototype deprecated

### ISSUE THREAD

**Issue by kyoongdev** [toss/nestjs-aop#21]
## src > auto-aspect-executor.ts

**AS-IS**
```ts
const methodNames = this.metadataScanner.scanFromPrototype(
        instance,
        Object.getPrototypeOf(instance),
        (name) => name,
);
```

**TO-BE**
```ts
const methodNames = this.metadataScanner.getAllMethodNames(instance);
```

=> method scanFromPrototype is deprecated

**Comment by WhiteKiwi** [comment]
세심한 제보 감사합니다 ㅎㅎ
![image](https://github.com/toss/nestjs-aop/assets/32415680/49bc6efe-f576-4cfa-8066-c6235c94b662)

nestjs 8~9 버전을 지원하다 보니 최신 기능을 사용하지 않도록 의도적으로 남겨두었어요
최근에 10이 나왔는데 10에서 없어졌다면 관련해서 대응 고민해보도록 하겠습니다 🙇
