### ISSUE TITLE
[BUG]: What is the licence? 

### ISSUE THREAD

**Issue by Sikora00** [toss/nestjs-aop#32]
In the `package.json` license is ISC while in the [LICENSE](https://github.com/toss/nestjs-aop/blob/v2.x/LICENSE) it says MIT.

Shouldn't it be the same one?

**Comment by WhiteKiwi** [comment]
It should be consistent. The default template(ISC) was not modified. The LICENSE file is correct. I will change package.json. Thank you for pointing it out! 👍
